# 自分のユーザー名とリポジトリ名
owner: WhiteJapan
repo: status

sites:
  - name: KBS Project
    # リポジトリではなく、公開されているWebサイトのURLがおすすめ
    url: https://github.com/WhiteJapan/kamohara-broadcasting-system

status-website:
  # カスタムドメイン（自分で買ったドメイン）を持っていないなら cname は消す！
  # cname: demo.upptime.js.org 
  
  # 代わりに自分のリポジトリ名をここに入れる（先頭の / を忘れずに）
  baseUrl: /status
  
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KBS Status Page
  introTitle: "KBS（Kamohara Broadcasting System）の稼働状況"
  introMessage: このページでは、システムの稼働状況をリアルタイムで公開しているよ。
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/WhiteJapan/kamohara-broadcasting-system
